version: '3'
services:
  # postgres:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "5432:5432"
  #   restart: always
  #   networks:
  #     - internal_network
  pbs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - internal_network

networks:
  internal_network:
    internal: true
